"""Effect execution logic.

Applies all nine EffectType values to game state, emitting appropriate events.
"""

from dataclasses import replace

from pydantic import ValidationError

from satori.events import (
    ActionLockedEvent,
    ActionUnlockedEvent,
    CaseEndedEvent,
    Event,
    FlagClearedEvent,
    FlagSetEvent,
    NodeActivatedEvent,
)
from satori.game_state import GameState
from satori.models.case_definition import CaseDefinition, Effect, EffectType, VitalSigns


class EffectExecutor:
    """Executes effects that modify game state."""

    def apply_effects(
        self, effects: list[Effect] | None, state: GameState, case: CaseDefinition
    ) -> tuple[GameState, list[Event]]:
        """Apply list of effects to state.

        Null-safe — if effects is None, returns state unchanged.

        Args:
            effects: List of effects to apply
            state: Current game state
            case: Case definition (for node lookups)

        Returns:
            Updated state and events generated by effects
        """
        if not effects:
            return state, []

        new_state = state
        events: list[Event] = []

        for effect in effects:
            new_state, effect_events = self._apply_single_effect(effect, new_state, case)
            events.extend(effect_events)

        return new_state, events

    def _apply_single_effect(
        self, effect: Effect, state: GameState, case: CaseDefinition
    ) -> tuple[GameState, list[Event]]:
        """Apply single effect.

        Handles ALL nine EffectType values.

        Args:
            effect: The effect to apply
            state: Current game state
            case: Case definition

        Returns:
            Updated state and events

        Raises:
            ValueError: If effect type is unknown
        """
        match effect.type:
            case EffectType.SET_FLAG:
                return self._set_flag(effect.target, state)
            case EffectType.CLEAR_FLAG:
                return self._clear_flag(effect.target, state)
            case EffectType.ACTIVATE_NODE:
                return self._activate_node(effect.target, state, case)
            case EffectType.DEACTIVATE_NODE:
                return self._deactivate_node(effect.target, state)
            case EffectType.MODIFY_TIMER:
                if effect.value is None:
                    raise ValueError(f"MODIFY_TIMER effect on '{effect.target}' requires an integer value")
                return self._modify_timer(effect.target, effect.value, state)
            case EffectType.UNLOCK_ACTION:
                return self._unlock_action(effect.target, state)
            case EffectType.LOCK_ACTION:
                return self._lock_action(effect.target, state)
            case EffectType.OVERRIDE_VITALS:
                return self._override_vitals(effect, state)
            case EffectType.END_CASE:
                return self._end_case(effect.target, state)
            case _:
                raise ValueError(f"Unknown effect type: {effect.type}")

    def _set_flag(self, flag: str, state: GameState) -> tuple[GameState, list[Event]]:
        """Add flag to state.flags.

        Emit FlagSetEvent.

        Args:
            flag: Flag name to set
            state: Current game state

        Returns:
            Updated state and events
        """
        if flag in state.flags:
            # Already set, no change
            return state, []

        new_flags = set(state.flags) | {flag}
        new_state = replace(state, flags=frozenset(new_flags))

        events: list[Event] = [FlagSetEvent(timestamp_minutes=state.current_time_minutes, flag=flag)]

        return new_state, events

    def _clear_flag(self, flag: str, state: GameState) -> tuple[GameState, list[Event]]:
        """Remove flag from state.flags.

        Emit FlagClearedEvent.

        Args:
            flag: Flag name to clear
            state: Current game state

        Returns:
            Updated state and events
        """
        if flag not in state.flags:
            # Not set, no change
            return state, []

        new_flags = set(state.flags) - {flag}
        new_state = replace(state, flags=frozenset(new_flags))

        events: list[Event] = [FlagClearedEvent(timestamp_minutes=state.current_time_minutes, flag=flag)]

        return new_state, events

    def _activate_node(self, node_id: str, state: GameState, case: CaseDefinition) -> tuple[GameState, list[Event]]:
        """Add node_id to active_nodes.

        If the node has a timer, initialize it in state.timers.
        Apply on_activate effects (from node.activation.on_activate).
        Emit NodeActivatedEvent.

        Must look up the Node from case.nodes to get timer config.
        Null-safe: check node.activation.on_activate is not None.

        Args:
            node_id: ID of node to activate
            state: Current game state
            case: Case definition

        Returns:
            Updated state and events
        """
        if node_id in state.active_nodes:
            # Already active, no change
            return state, []

        # Find the node
        node = next((n for n in case.nodes if n.id == node_id), None)
        if not node:
            # Node not found, no change
            return state, []

        new_active = set(state.active_nodes) | {node_id}
        new_state = replace(state, active_nodes=frozenset(new_active))

        # Initialize timer if present
        if node.timer:
            new_timers = dict(state.timers)
            new_timers[node_id] = node.timer.duration_minutes
            new_state = replace(new_state, timers=new_timers)

            # Initialize timer_stages tracking (starts at 0)
            new_timer_stages = dict(state.timer_stages)
            new_timer_stages[node_id] = 0
            new_state = replace(new_state, timer_stages=new_timer_stages)

        events: list[Event] = [
            NodeActivatedEvent(
                timestamp_minutes=state.current_time_minutes,
                node_id=node_id,
                node_type=node.type,
            )
        ]

        # on_activate effects will be handled by the caller
        # (to avoid circular dependency with apply_effects)

        return new_state, events

    def _deactivate_node(self, node_id: str, state: GameState) -> tuple[GameState, list[Event]]:
        """Remove node_id from active_nodes.

        Clean up its timer if present.

        Args:
            node_id: ID of node to deactivate
            state: Current game state

        Returns:
            Updated state and events
        """
        if node_id not in state.active_nodes:
            # Not active, no change
            return state, []

        new_active = set(state.active_nodes) - {node_id}
        new_state = replace(state, active_nodes=frozenset(new_active))

        # Clean up timer if exists
        if node_id in state.timers:
            new_timers = dict(state.timers)
            new_timers.pop(node_id, None)
            new_state = replace(new_state, timers=new_timers)

            new_timer_stages = dict(state.timer_stages)
            new_timer_stages.pop(node_id, None)
            new_state = replace(new_state, timer_stages=new_timer_stages)

        # No event for deactivation (not in spec)
        return new_state, []

    def _modify_timer(self, node_id: str, value: int, state: GameState) -> tuple[GameState, list[Event]]:
        """Add value to the timer for node_id.

        Positive value = extend timer (more time).
        Negative value = accelerate timer (less time, approaching expiry).

        Example: node_08's on_expire does modify_timer on node_06 with value=-60,
        meaning steroids accelerate the headache progression by 60 minutes.

        Args:
            node_id: ID of node with timer
            value: Minutes to add (positive) or subtract (negative)
            state: Current game state

        Returns:
            Updated state and events
        """
        if node_id not in state.timers:
            # No timer, no change
            return state, []

        new_timers = dict(state.timers)
        current_remaining = new_timers[node_id]
        new_remaining = current_remaining + value

        # Clamp to 0 minimum
        new_remaining = max(0, new_remaining)

        new_timers[node_id] = new_remaining
        new_state = replace(state, timers=new_timers)

        # No event for timer modification (implicit in next timer advance)
        return new_state, []

    def _unlock_action(self, action: str, state: GameState) -> tuple[GameState, list[Event]]:
        """Add action to available_actions.

        Emit ActionUnlockedEvent.

        Args:
            action: Action to unlock
            state: Current game state

        Returns:
            Updated state and events
        """
        if action in state.available_actions:
            # Already available, no change
            return state, []

        new_actions = set(state.available_actions) | {action}
        new_state = replace(state, available_actions=frozenset(new_actions))

        events: list[Event] = [ActionUnlockedEvent(timestamp_minutes=state.current_time_minutes, action=action)]

        return new_state, events

    def _lock_action(self, action: str, state: GameState) -> tuple[GameState, list[Event]]:
        """Remove action from available_actions.

        Emit ActionLockedEvent.

        Args:
            action: Action to lock
            state: Current game state

        Returns:
            Updated state and events
        """
        if action not in state.available_actions:
            # Not available, no change
            return state, []

        new_actions = set(state.available_actions) - {action}
        new_state = replace(state, available_actions=frozenset(new_actions))

        events: list[Event] = [ActionLockedEvent(timestamp_minutes=state.current_time_minutes, action=action)]

        return new_state, events

    def _override_vitals(self, effect: Effect, state: GameState) -> tuple[GameState, list[Event]]:
        """Override specific vital signs directly.

        effect.target = vital name (e.g., "heart_rate")
        effect.value = new value

        Sets the vital directly on current_vitals, bypassing worst-wins.

        Args:
            effect: The override effect
            state: Current game state

        Returns:
            Updated state and events
        """
        vital_name = effect.target
        new_value = effect.value

        # Create new vitals with the override
        current_vitals_dict = {
            "heart_rate": state.current_vitals.heart_rate,
            "blood_pressure_systolic": state.current_vitals.blood_pressure_systolic,
            "blood_pressure_diastolic": state.current_vitals.blood_pressure_diastolic,
            "temperature": state.current_vitals.temperature,
            "respiratory_rate": state.current_vitals.respiratory_rate,
            "o2_saturation": state.current_vitals.o2_saturation,
        }

        if vital_name in current_vitals_dict:
            current_vitals_dict[vital_name] = new_value

        try:
            new_vitals = VitalSigns.model_validate(current_vitals_dict)
        except ValidationError as exc:
            # A malformed authored value would otherwise crash mid-simulation
            # with an opaque Pydantic error; name the offending effect instead.
            raise ValueError(f"OVERRIDE_VITALS effect on '{vital_name}' has invalid value {new_value!r}") from exc
        new_state = replace(state, current_vitals=new_vitals)

        # Vitals change event will be emitted by engine's _recompute_vitals
        return new_state, []

    def _end_case(self, outcome_tier: str, state: GameState) -> tuple[GameState, list[Event]]:
        """End the case with the given outcome tier.

        Set case_ended=True, outcome_tier, and emit CaseEndedEvent.

        Args:
            outcome_tier: The outcome tier (OutcomeTierLevel value)
            state: Current game state

        Returns:
            Updated state and events
        """
        if state.case_ended:
            # Already ended, no change
            return state, []

        new_state = replace(
            state,
            case_ended=True,
            outcome_tier=outcome_tier,
            end_reason=f"Triggered by END_CASE effect: {outcome_tier}",
        )

        events: list[Event] = [
            CaseEndedEvent(
                timestamp_minutes=state.current_time_minutes,
                outcome_tier=outcome_tier,
                end_reason="Triggered by END_CASE effect",
            )
        ]

        return new_state, events
